### ISSUE TITLE
On close of browser, again credentials are required at IDP side

### ISSUE THREAD

**Issue by sunilx64** [onelogin/python3-saml#101]
Greetings,

I have configured python3-saml in my django application. it is working fine. 
But on the close of browser it is asking agin user credentials at IDP (ADFS) server. 

P.S :- same IDP is being used for other applications and there it is working fine for them.

**Comment by platipusica** [comment]
Hi, 

I did configure Flask example with Shibboleth IdP, and working fine on close. But I'm puzzled wit Django, can you share your experience with your app, how did you manage to make it work?

Thx

**Comment by sunilx64** [comment]
@platipusica :- instead of checking whether session is still alive, i was always routing the request to idp server for authentication.
