### ISSUE TITLE
Hard time verifying signature when certificate is signed by CA

### ISSUE THREAD

**Issue by gpalyan** [onelogin/python3-saml#112]
I am trying to use the method: OneLogin_Saml2_Utils.validate_metadata_sign to validate a metadata response. The XS.509 certificate in that response is signed by a CA (DigiCert I believe). Here is the response: https://sp.auth-staging.adobe.com/sp/saml/metadata. When attempting to verify, I get an error like this:

func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=346:obj=x509-store:subj=unknown:error=71:certificate verification failed:X509_verify_cert: subject=/C=US/ST=California/L=San Jose/O=Adobe Systems Incorporated/CN=saml.sp.auth.adobe.com; issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA; err=20; msg=unable to get local issuer certificate

I get a similar error with xmlsec1:

xmlsec1 --verify metadata.xml 
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=346:obj=x509-store:subj=unknown:error=71:certificate verification failed:X509_verify_cert: subject=/C=US/ST=California/L=San Jose/O=Adobe Systems Incorporated/CN=saml.sp.auth.adobe.com; issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA; err=20; msg=unable to get local issuer certificate
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=385:obj=x509-store:subj=unknown:error=71:certificate verification failed:subject=/C=US/ST=California/L=San Jose/O=Adobe Systems Incorporated/CN=saml.sp.auth.adobe.com; issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA; err=20; msg=unable to get local issuer certificate
func=xmlSecKeysMngrGetKey:file=keys.c:line=1253:obj=unknown:subj=xmlSecKeysMngrFindKey:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessKeyInfoNode:file=xmldsig.c:line=795:obj=unknown:subj=unknown:error=45:key is not found:details=NULL
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=508:obj=unknown:subj=xmlSecDSigCtxProcessKeyInfoNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=346:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed: 
Error: signature failed 
ERROR
SignedInfo References (ok/all): 0/0
Manifests References (ok/all): 0/0
Error: failed to verify file "metadata.xml"

With xmlsec1, the problem seems to be solved when I provide the certificate of the Certificate Authority (e.g.):

xmlsec1 --verify --trusted-pem ca.pem metadata.xml 
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0

But doing something similar with your code (i.e. providing the CA cert) still results in error. There is a  very good chance I'm doing something wrong, but I thought I'd ask to see if you can provide any direction. Thanks in advance.

**Comment by pitbulk** [comment]
When you use the --trusted-pem you say to the xmlsec1 utility to trust the certificate and don't validate it.

If you review the [validate_metadata_sign method](https://github.com/onelogin/python3-saml/blob/db1e9a6417511a49fdae42c44a3a386267d8bb16/src/onelogin/saml2/utils.py#L864) you will find that there is a 'validatecert' parameter that is supposed to be used to avoid the cert validation (by default its value is false). Are you using that parameter?

**Comment by gpalyan** [comment]
Actually, I did some more investigation and the root cause seems to be that this metadata response has a blank URI field: <ds:Reference URI="">

        if len(reference_elem) > 0:
            if reference_elem[0].get('URI') == '':
                reference_elem[0].set('URI', '#%s' % signature_node.getparent().get('ID'))

When I comment out following code, it seems to verify the signature correctly. I am even able to set validatecert=True and that works as well once I chain the certificates together. I'm not sure if this is a bug on the part of Adobe, but at least in their metadata response, they omit this field.

**Comment by gpalyan** [comment]
I had another question if I may:

I am trying to understand how to integrate with the method:

OneLogin_Saml2_Utils:validate_binary_sign

Suppose I have a request like such:

SAMLRequest=fZJRb5swEMff9yksvxswS5rOClRZo2qRuo01dA97mYw5WktgM5%2FJ1m8%2FA2XKNC2vcPe7n%2B9%2F25tfXUtO4FBbk1EeJZSAUbbW5imjj%2BUdu6Y3%2BZstyq5Ne7Eb%2FLN5gB8DoCc7RHA%2B9N1ag0MH7gjupBU8Ptxn9Nn7HkUcYx%2FJ0MTQy6fAjGRtK4iU7cKfeKTGx93H%2B39QlOzDCG2kn7wWmq77mdBLxJkyIia7GNFScmedgkkzo94NQMlhn9HvvKpgk24Uq3lTs1W6Sln17u2KVet63VypdZooHkqxCFx9gow2ssWxGXGAgwn2xmc0Tfg14wlLeJlywTci4RG%2FSr5RUjjrrbLte23m1Q3OCCtRozCyAxReifGhIo0SUc1FKD6UZcGKz8eSkq9LBOkYQQjFoJiXfpnVvw6m%2BZyRmIzdOeEyQC6rp%2FmfzEJX9N%2FgtvH5oHw5jU%2BBfNgXttXqheza1v68dSA9LDGEYDrpL7uMX3TNmqlUeCcNajCekmMx4r8MstWNBnd2XhdVaZy%2F2v59uvlv&RelayState=_346aeb89-7923-49b0-9517-b6544f58f14d&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1&Signature=FzEpeMDRdnAol9x6ULxKFdruSXbkAnhJzG156WCschl53DkHW4RjxzfWDfy2fRNYFhmMF6oSOWvCJJd5MKaYWtmzxMtTPQtlAtn1pNNfLEoTv63yI%2FU90v2Uo0gWdOaY%2BTNSszKSe4WyXb5XMQE6U25MMlmtkRgxzyXjQ7awmar0cz6vVNLa9rQaIb2zYzsFmdykgyoJpsVFG58kvqAvRCffg3LI5j24qfEefkiUQHmYu1FikrsC68FL5uly%2FzcxcMnj5aJInaYn9GV9hs2J9TAwNVHLohGhiA%2FIZ8dFhpRoRk15cg%2BuzbapTpXejH1HSnYJ%2FEPqCT0R3DWyUY3YQA%3D%3D

Is the signed_query param (SAMLRequest=...&RelayState=...&SigAlg=...) as is, or do I need to urldecode those params, and for SAMLRequest do I also have to base64 decode and decompress to get actual XML String.

Also, for the signature, do I again need to urldecode and base64 decode. I'm a bit confused about the integration detail.

**Comment by gpalyan** [comment]
Any feedback on my previous question?

**Comment by gpalyan** [comment]
I was able to figure out from your unit tests how the function is used and it seemed to work.
