### ISSUE TITLE
Tests missing from PyPI

### ISSUE THREAD

**Issue by jtojnar** [onelogin/python3-saml#115]
I am trying to package python3-saml for NixOS but cannot run tests because the PyPI package lacks them.

See also the Debian thread about the issue:
https://lists.debian.org/debian-python/2016/04/msg00074.html

```
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/nix/store/s3nl02c26303mfjvaaxnc19f8ks9hc8c-python3-3.6.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests'
```

**Comment by pitbulk** [comment]
We intentionally removed the test because we saw end users directly serving the library + test on their productions deployments.

As suggested in the thread you shared, you can always use git archive.

[See examples of use](https://gist.github.com/kristofferh/1442717)

**Comment by jayvdb** [comment]
You already serve your end users needs by [https://pypi.org/simple/python3-saml/ supplying wheels].  They dont use the sdist.

**Comment by jayvdb** [comment]
I notice you are including python2 wheels in this python3 package.  Is that correct?  The other repo seems active still, so I guess you dont want this package installed on python2.

**Comment by pitbulk** [comment]
python3-saml is compatible with p2 and p3
python-saml is compatible only with p2
