### ISSUE TITLE
Need ignore-zip in logout_response.__init__

### ISSUE THREAD

**Issue by psz2036** [onelogin/python3-saml#120]
I seem to get good results with SAML (building an SP, working with my
University's IdP which apparently is ADFS), except... that SLO (or is it SLS?)
shows error:

Traceback (most recent call last):
  File "/users/amstaff/psz/saml/saml.py", line 193, in <module>
    x= auth.process_slo()
  File "/users/amstaff/psz/.local/lib/python3.5/site-packages/onelogin/saml2/auth.py", line 144, in process_slo
    logout_response = OneLogin_Saml2_Logout_Response(self.__settings, get_data['SAMLResponse'])
  File "/users/amstaff/psz/.local/lib/python3.5/site-packages/onelogin/saml2/logout_response.py", line 41, in __init__
    self.__logout_response = compat.to_string(OneLogin_Saml2_Utils.decode_base64_and_inflate(response))
  File "/users/amstaff/psz/.local/lib/python3.5/site-packages/onelogin/saml2/utils.py", line 110, in decode_base64_and_inflate
    return zlib.decompress(encoded, -15)
zlib.error: Error -3 while decompressing data: invalid code lengths set

Seems that the error is solved by the one-line patch:

--- .local--GOOD/lib/python3.5/site-packages/onelogin/saml2/logout_response.py  2018-11-16 10:24:54.912294631 +1100
+++ .local/lib/python3.5/site-packages/onelogin/saml2/logout_response.py        2018-10-28 08:40:37.065844297 +1100
@@ -26,31 +26,31 @@
     def __init__(self, settings, response=None):
         """
         Constructs a Logout Response object (Initialize params from settings
         and if provided load the Logout Response.
 
         Arguments are:
             * (OneLogin_Saml2_Settings)   settings. Setting data
             * (string)                    response. An UUEncoded SAML Logout
                                                     response from the IdP.
         """
         self.__settings = settings
         self.__error = None
         self.id = None
 
         if response is not None:
-            self.__logout_response = compat.to_string(OneLogin_Saml2_Utils.decode_base64_and_inflate(response, ignore_zip=True))
+            self.__logout_response = compat.to_string(OneLogin_Saml2_Utils.decode_base64_and_inflate(response))
             self.document = OneLogin_Saml2_XML.to_etree(self.__logout_response)
             self.id = self.document.get('ID', None)
 
     def get_issuer(self):
         """
         Gets the Issuer of the Logout Response Message
         :return: The Issuer
         :rtype: string
         """
         issuer = None
         issuer_nodes = self.__query('/samlp:LogoutResponse/saml:Issuer')
         if len(issuer_nodes) == 1:
             issuer = OneLogin_Saml2_XML.element_text(issuer_nodes[0])
         return issuer
 
With the patch, my SP seems to work perfectly.

Cheers, Paul
Paul Szabo   psz@maths.usyd.edu.au   http://www.maths.usyd.edu.au/u/psz/
School of Mathematics and Statistics   University of Sydney    Australia

**Comment by pitbulk** [comment]
Isn't that solved by https://github.com/onelogin/python3-saml/commit/01166a135ac5c50806c57ce9d1819ee1d187b689?

**Comment by psz2036** [comment]
Yes, exact same issue (including the GET/POST confusion). - I had installed the "official release" (with pip3) about a month ago; did not see the issue as outstanding when checking yesterday (nor did I check whether there was a newer version of the software). - Sorry about the noise.
