### ISSUE TITLE
Create minor release with bug fixes from PR#127

### ISSUE THREAD

**Issue by phyro** [onelogin/python3-saml#131]
Would it be possible to create a minor release with https://github.com/onelogin/python3-saml/pull/127 ?
Thanks!

**Comment by phyro** [comment]
cc: @pitbulk

**Comment by pitbulk** [comment]
Yes, I plan to add a new feature this week, so expect a new release in 4-8 days

**Comment by phyro** [comment]
@pitbulk thanks for the fast response and release info :+1: I'll close the issue once the release is out if that's ok with you

**Comment by phyro** [comment]
hey @pitbulk how's the release looking?

**Comment by pitbulk** [comment]
Sorry for the delay, hope to release it very soon.

**Comment by pitbulk** [comment]
1.6.0 released
https://pypi.org/project/python3-saml/

**Comment by phyro** [comment]
thanks, much appreciated!
