### ISSUE TITLE
Multiple IDPs?

### ISSUE THREAD

**Issue by nhill-cpi** [onelogin/python3-saml#132]
Is there a way to configure settings to make this library work with one of several IDPs? In other words, in my middleware, is it possible to specify which certificate (among many) I want to use to verify communication with the IDP?

Thanks!

**Comment by pitbulk** [comment]
Yes, the settings can be provided dynamically so depending on the endpoint/parameter, you can load a specific setting related to a specific IdP.

See for example that implementation:
https://github.com/MindPointGroup/django-saml2-pro-auth

**Comment by nhill-cpi** [comment]
Thank you.
