### ISSUE TITLE
AuthNRequestID only compared to InResponseTo value if latter is present

### ISSUE THREAD

**Issue by volker-travelperk** [onelogin/python3-saml#139]
The comparison between the AuthNRequestID to the InResponseTo value is only performed, if both are not None:
https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L126

I might have missed a detail, but thus, if InResonseTo is not present in the response this check wouldn't be performed, though user might expect it to be done.

Is this a desired behaviour?

**Comment by pitbulk** [comment]
InResponseTo is an optional attribute of the SAMLResponse and request_id is also optional on the toolkit.

Think for example on the IdP-initiated SSO flow, the SAMLResponse is directly sent to SP.

If the SP wants to always reject unexpected SAMLResponses, that can be done by storing a list of IDs of AuthNRequests and verify that the SAMLResponse ID matches one of the stored values. But this can be done at top-level

**Comment by volker-travelperk** [comment]
Got it! Thanks!
