### ISSUE TITLE
support sign-then-encrypt for SAMLResponse

### ISSUE THREAD

**Issue by haoleman** [onelogin/python3-saml#142]
I am in the process of pushing up a PR to support encrypt-then-sign (current) AND sign-then-encrypt for a SAMLResponse, as I need to support multiple IDP's with these different configurations. It will default to encrypt-then-sign, but can set in advanced_settings. Everything works fine. I am just putting together some tests. However, I don't readily see the private key you all use to create the base64 encoded SAMLResponses (ie: idp.key).... so I can generate new sign-then-encrypt SAMLResponses.

Would it be possible to get that test key?  Or just push up the PR and you can put together tests for sign-then-encrypt? This seems like a needed feature in the baseline, but I can just fork if this is not something you'd merge in.

**Comment by pitbulk** [comment]
I don't get what you are trying to provide in the PR.

The process to validate the most complex case: A Signed Message with an encrypted signed assertion is covered:
1. Validate Signature of the Response element  
2. Decrypt the assertion
3. Validate Signature of the Assertion.

If you to 1st decrypt and then validate the signature, then the validation process will fail because the content changed. the standard is clear about the steps to sign/encrypt validate/decrypt, so I don't get what are you trying to achieve.

**Comment by haoleman** [comment]
It covers the case of a Signed Message with an encrypted assertion....but the creation of the SAMLResponse is sign-then-encrypt (not encrypt-then-sign):
1. Sign the entire SamlResponse
2. Encrypt the Assertion

So, when validating the SAMLResponse the process needs to be:
1. Decrypt the Assertion
2. Validate Signature of the SAMLResponse

This will fail with current version of library. PR can either introduce a "messageSigningOrder" or have a try/except to cover this case.

**Comment by pitbulk** [comment]
This extension assumes the encrypt-element then sign-container/element principle.
What IdP are you using that implements a different process?

The order of operations at the IdP must be:

1. Sign the Assertion if enabled this option
2. Encrypt the Assertion if enabled this option
3. Sign the Response if enabled this option

At the SP it must be basically the reverse:

1) validate the signed Response
2) decrypt the EncryptedAssertion(s)
3) validate the signed (and decrypted) Assertion(s)

**Comment by pitbulk** [comment]
The order of operations depends on the element:

- Signed Assertion
  - Encrypted Assertion
     - Sign then encrypt
  - Encrypted NameIdentifier & Attribute
     - Encrypt then sign
- Signed Request or Response
     - Encrypt then sign

**Comment by haoleman** [comment]
Thank you, for all the information. Sounds like a great library, to support onelogin.  Closing issue due to encrypt-then-sign is a must.
