### ISSUE TITLE
Handling IdP signing key rollover?

### ISSUE THREAD

**Issue by jtwolgamott** [onelogin/python3-saml#145]
The README states the following regarding IdP key rollover:

_In some scenarios the IdP uses different certificates for
signing/encryption, or is under key rollover phase and
more than one certificate is published on IdP metadata.
**In order to handle that the toolkit offers that parameter.**
(when used, 'X.509cert' and 'certFingerprint' values are
ignored)._

What is meant by "In order to handle that the toolkit offers that parameter"? I don't see anything in the documentation regarding this parameter, and my IdP (Azure AD) periodically performs signing key rollover without notification. How can I handle key rollover without manually editing the `settings.json` to add the new IdP signing keys?

**Comment by pitbulk** [comment]
Id the 'x509certMulti' parameter described in the documentation at the [settings section](https://github.com/onelogin/python3-saml#settings)
```
        /* In some scenarios the IdP uses different certificates for
         * signing/encryption, or is under key rollover phase and
         * more than one certificate is published on IdP metadata.
         * In order to handle that the toolkit offers that parameter.
         * (when used, 'X.509cert' and 'certFingerprint' values are
         * ignored).
         */
        // 'x509certMulti': {
        //      'signing': [
        //          '<cert1-string>'
        //      ],
        //      'encryption': [
        //          '<cert2-string>'
        //      ]
        // }
```

In order to avoid manually update the settings with the new certs, the toolkit offers the [idp_metadata_parser.py](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/idp_metadata_parser.py) script that you can use in order to retrieve IdP metadata, including public certs. You can use a cron to execute that script time to time and update the settings file in an automated way.

**Comment by jtwolgamott** [comment]
Thanks @pitbulk, that's what I'm trying to do currently, but I'm encountering issues with updating the `settings.json` file because my app is containerized, and this creates somewhat of a weird stateful process that's not very container friendly. It would be great if I could simply pass in specific attributes of `settings.json` through the `OneLogin_Saml2_Auth()` constructor, but this doesn't appear to be supported?

**Comment by pitbulk** [comment]
You don't need the settings.json file at all.

You can initialize the [OneLogin_Saml2_Auth](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/auth.py#L27) object with the old_settings parameter containing the dict with settings values.

Internally it will executes
```
self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
``` 
and the [settings object](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/settings.py#L62) will be initialized with the dict

**Comment by jtwolgamott** [comment]
Great, thank you! That's just what I was looking for.

**Comment by nhill-cpi** [comment]
@pitbulk Is there a way to dynamically call `OneLogin_Saml2_IdpMetadataParser.parse_remote()` in my middleware? I would rather not run a cron job to update IDP certs.
