### ISSUE TITLE
CSRF cookie not set

### ISSUE THREAD

**Issue by VdeJong** [onelogin/python3-saml#146]
As soon as I try to login using Google SSO on my python/django application I am redirected by Google to the ACS url but it gives me a forbidden 403 error. It says `csrf cookie not set`.

**Comment by pitbulk** [comment]
https://stackoverflow.com/questions/22812721/why-do-i-get-csrf-cookie-not-set-when-post-to-django-rest-framework?rq=1

**Comment by VdeJong** [comment]
@pitbulk no I'm not as I thought it is not safe to bypass the csrf. But are you saying that is necessary for this to work?

**Comment by pitbulk** [comment]
Is safe to bypass csrf on that particular ACS endpoint.
Notice that the POST came from a 3rd party system that is not able to generate a valid CSRF value.
Also noticed that the SAML standard has its own mechanism to validate the SAMLResponse generated by the 3rd party (IdP).

**Comment by VdeJong** [comment]
Alright.
Thanks for your clear explanation and fast reply.
