### ISSUE TITLE
Cannot extract Attributes from Azure Active Directory SAML response

### ISSUE THREAD

**Issue by bharling** [onelogin/python3-saml#154]
Hi,

I'm struggling to extract assertions from a SAML response issued from Azure active directory, I'm a bit of a newb at this generally but I think it's because Azure isn't namespacing the assertions. I've tested our implementation successfully with other IDPs like testshib and onelogin, and have got an integration almost working with Azure AD except it cannot extract any of the assertions.

a working ssocircle assertion looks like this:

```
            <saml:Attribute Name="FirstName">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">Ben
                </saml:AttributeValue>
            </saml:Attribute>
```

But Azure sends unprefixed tags like:

```
            <Attribute Name="givenname">
                <AttributeValue>Ben</AttributeValue>
            </Attribute>

```

This is the only difference that I can see, the rest of the IDP integration seems to work fine. I can see in code for python3-saml the respose.get_attributes() method seems to expect the namespace to be present, is there some way to set this up to be able to cope with non-prefixed and prefixed versions?

thanks for any help...

**Comment by bharling** [comment]
Closing, apologies - was due to stale cookies during the auth redirect process during testing.

**Comment by wonderchang** [comment]
I'm working with AAD to implement SSO but I can't extract those attributes either. I think the problem is, as you mentioned above, lack of `saml` namespace in the SAML response.

Is that the problem, right? But why it has something to do with the stale cookie? Does anyone also suffer from this problem?

**Comment by pitbulk** [comment]
Use [SAML tracer](https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/ to record the SAMLResponse and verify that the Attributes are there.

**Comment by CatMao1230** [comment]
@pitbulk Thanks for your reply.

Actually we have got `<Attribute>` . 
But according to source code, it seems like query by `<saml:Attribute>` .

So when we use `get_attributes()` , it got an empty dictionary.
