### ISSUE TITLE
Add logging to ease debugging (re-raised from python-saml)

### ISSUE THREAD

**Issue by bivald** [onelogin/python3-saml#161]
Hi,

Would you be open to pull requests that increases logging instead of using print? My reasoning is similar to https://github.com/onelogin/python-saml/issues/98. What typically happens for me during implementation is that I hack response.py and add logging all over the place to find the miss-configuration.

I'm just looking for if you would accept such pull requests, before I put any time on them :)

Thank you for a great library

Regards,
Niklas

**Comment by pitbulk** [comment]
I'm open for a solution where the default log system will be the print way, and that log system can be extended by a more sophisticated one. But I don't want to link the library to a specific log.

**Comment by bivald** [comment]
I would recommend the traditional python logging system since that's the most commonly used. I'm closing this since its no use keeping it open :)
