### ISSUE TITLE
handle timestamps that have a 7 digit microsecond on SAML assertions

### ISSUE THREAD

**Issue by arosswilson** [onelogin/python3-saml#163]
Hi all, 

first of all, thank you so much for all of your work on this project!

I'm testing SSO and one of our Identity providers is sending us a timestamp with a seven digit microsecond in the assertion. It seems like they aren't able to adjust that on their end.

When we process the response, we're getting the following error: `time data '2019-09-17T22:26:00.7716268Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`

Do you have any suggestions on the best way to handle this?

Thanks for the help!

**Comment by pitbulk** [comment]
Try overriding the [parse_SAML_to_time](https://github.com/onelogin/python3-saml/blob/29e1b51c1d830e1dd4c08455fcdb268d20bf7f36/src/onelogin/saml2/utils.py#L407) method.

Catch the line:
```
data = datetime.strptime(timestr, '%Y-%m-%dT%H:%M:%S.%fZ')
```
And search some format that matches the format your IdP sends.

**Comment by pitbulk** [comment]
Fixed here: https://github.com/onelogin/python3-saml/commit/5f162dc9947bb34cd7502177f35e4edbf9a477dd
