### ISSUE TITLE
Replace Session Cookie for a Token

### ISSUE THREAD

**Issue by Sleepy105** [onelogin/python3-saml#164]
I'm using JWT tokens for access to my website's API, so when the users log in through SSO I just hand them a token.
With that, I don't use the session cookie for anything else other than to store the SSO data:
- AuthNRequestID
- samlUserdata
- samlNameId
- samlNameIdFormat
- samlNameIdNameQualifier
- samlNameIdSPNameQualifier
- samlSessionIndex
- LogoutRequestID

I was thinking of foregoing the session cookie and placing this data on the user's localStorage, and on every request and response to any SSO endpoint, receive and update that data.

Are there any security implications to this scheme? Is there a problem if the user just deletes the data mid-session (I'm guessing the only implication is the inability to complete a SLO)?
Can you offer any further thoughts on this?

**Comment by pitbulk** [comment]
Browser local storage (or session storage) is not a secure place to store sensitive information. Any data stored there:
- Can be accessed through JavaScript.
- May be vulnerable to cross-site scripting.

See https://dev.to/rdegges/please-stop-using-local-storage-1i04
