### ISSUE TITLE
acs as a sperate view

### ISSUE THREAD

**Issue by habi3000** [onelogin/python3-saml#167]
Hello onelogin team, 
I have a question regarding django demo. sso, sso2, slo, acs, and sls are under the same view. I was thinking about putting acs in sperate view that would allow  us to enable scrf on the index view and disable it for acs. Is not this better than disabling scrf middleware ?

**Comment by pitbulk** [comment]
Yes, you can split the actions in different views. The demo was built as a unique view to keep it simple.
The CSRF protection must be disabled on the ACS view because it receives POST data.

**Comment by habi3000** [comment]
may I make a PR ?
