### ISSUE TITLE
utility function add_sign() issue

### ISSUE THREAD

**Issue by Vinod83GH** [onelogin/python3-saml#168]
We are working on IDP initiated SAML flow. When we validate signed saml assertion response using online saml validator tool, we always get error "Signature validation failed. Reference validation failed". By looking at the differences in saml response we generate using saml online tool and the once we created using , module - utils.py, method - add_sign() we found that the VALUE of nodes <X509Certificate> & </SignatureValue> value has spaces generated by our code. but not through online tool. Not sure this is the reason or something tat we are missing. Please find attached SAML unsigned response and signed response + private key and public key that we used. Signed response using code which is using the python-3-saml package method in module utils.py - "add_sign()"

All the required saml response related xml and certificates/key are ain attached doc - 
saml_response_all_code.docx

[saml_response_all_code.docx](https://github.com/onelogin/python3-saml/files/3834919/saml_response_all_code.docx)

**Comment by Vinod83GH** [comment]
Can we get the solution to this issue ASAP, as we have PROD release on Thursday. Any help will be appreciated a lot.

**Comment by pitbulk** [comment]
Sending the XML in plain text is useless. A simple extra line/space in the XML will produce a Signature Validation failure.

How are you retrieving the signed XML? Maybe when you print it, you are formating it and that invalidates the Signature verification process.

Rather than validate the XMl with the samltool site, have you tried a real IdP?

Other customers are using the toolkit with no issue so I don't think there is an issue on the add_sign method.

**Comment by Vinod83GH** [comment]
I am validating the generated response xml using saml toolkit site itself. And i get error 'Signature validation failed. Reference validation failed'. Please find attached my saml raw response, which is saved in xml file after generation without any formatting. there is no formatting done here. please check my saml response below - 
--------------------
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:enc="http://www.w3.org/2001/04/xmlenc#" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Destination="https://DOMAIN-DEST-SITE-URL/sso/saml/acs/" ID="id-2d56d182-fdd6-41d3-b4fc-45b5059b7b4e" IssueInstant="2019-11-12T06:08:26.915Z" Version="2.0">
    <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://DOMAIN-SITE-URL/sso/saml/</saml:Issuer><samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </samlp:Status>
    <saml:Assertion ID="id-a56033b7-db55-48f4-b3b6-88b1bba7aae2" IssueInstant="2019-11-12T06:08:26.915Z" Version="2.0">
        <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://DOMAIN-SITE-URL/sso/saml/</saml:Issuer><dsig:Signature>
<dsig:SignedInfo>
<dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<dsig:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<dsig:Reference URI="#id-a56033b7-db55-48f4-b3b6-88b1bba7aae2">
<dsig:Transforms>
<dsig:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</dsig:Transforms>
<dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<dsig:DigestValue>fvHYUgU/xgenUruWJmdUCGyCG+E=</dsig:DigestValue>
</dsig:Reference>
</dsig:SignedInfo>
<dsig:SignatureValue>jKwHl5Q1eT4SmtEILqhGh/3Kk5u9OZYZQOHnfQRzhYWm0bF9Sl2D1XZ8m1a4HHxs
BJXa+9/hOHGofMvdOqrOmpl2AFBemKAXnOMJjJO8Elkd47VipU1vXqjEQjsLXvpU
9sbSQNv1/RaoCfV9jHd8gIc4CQTVpK0QGImEhZrmoJw=</dsig:SignatureValue>
<dsig:KeyInfo>
<dsig:X509Data>
<dsig:X509Certificate>MIICpTCCAg4CCQD+OuNoqDP4czANBgkqhkiG9w0BAQUFADCBljELMAkGA1UEBhMC
SU4xEjAQBgNVBAgMCUtBUk5BVEFLQTESMBAGA1UEBwwJQkFOR0FMT1JFMQ0wCwYD
VQQKDARHQUxFMQswCQYDVQQLDAJJVDEdMBsGA1UEAwwUd3d3LmdhbGVwYXJ0bmVy
cy5jb20xJDAiBgkqhkiG9w0BCQEWFWluZm9AZ2FsZXBhcnRuZXJzLmNvbTAeFw0x
OTEwMjkxNjI3MjRaFw0yMDEwMjgxNjI3MjRaMIGWMQswCQYDVQQGEwJJTjESMBAG
A1UECAwJS0FSTkFUQUtBMRIwEAYDVQQHDAlCQU5HQUxPUkUxDTALBgNVBAoMBEdB
TEUxCzAJBgNVBAsMAklUMR0wGwYDVQQDDBR3d3cuZ2FsZXBhcnRuZXJzLmNvbTEk
MCIGCSqGSIb3DQEJARYVaW5mb0BnYWxlcGFydG5lcnMuY29tMIGfMA0GCSqGSIb3
DQEBAQUAA4GNADCBiQKBgQDCOyNNytL3Dmiww6i7KIoOjCCgIGw+QhWw46TbMhWt
8O4hDjE+bOAKvpPO1xj+p2aDGXrhfK20DXcMd7yNjJKwI8ykqhxeF/49qHKgKZVI
3DQF5YSMYtrnsfTr2teIzLGOdVoKDSAffWkE4Cye0d6sGeEemZL4p3LJfTuMIjq0
xwIDAQABMA0GCSqGSIb3DQEBBQUAA4GBAFoHi2wi62LPzQTef7/I0wKKW5kSJ42i
RIM6f/fpmy6agCuvf4ge0w6ARxDaBcjCrcHW41fdkxQht5XabU1Ivn842Sx+te+Z
Jj2Eq3ozB6MJz2cubVlzzlCsq2GQWe+VfTv/3iC6KCF1hQ5I4TjyuAeD0OH+4YAD
hTMqGDNc+SqK</dsig:X509Certificate>
</dsig:X509Data>
</dsig:KeyInfo>
</dsig:Signature><saml:Subject>
            <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">NAME_ID_VALUE</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData NotOnOrAfter="2019-11-12T06:13:26.916Z" Recipient="https://DOMAIN-DEST-SITE-URL/sso/saml/acs/"/>
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2019-11-12T06:08:26.915Z" NotOnOrAfter="2019-11-12T06:13:26.916Z">
            <saml:AudienceRestriction>
                <saml:Audience>https://DOMAIN-DEST-SITE-URL/sso/saml/metadata/</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2019-11-12T06:08:26.915Z" SessionIndex="id-a56033b7-db55-48f4-b3b6-88b1bba7aae2">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="RelayState" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">https://DOMAIN-DEST-SITE-URL/path/</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>

------------------------------

**Comment by pitbulk** [comment]
As you can see github corrupted your SAMLResponse, the unique way to send the original SAMLResponse is by providing its base64 encoded value.

but, instead of trying to validate the SAMLResponse outside the python-saml tool, why don't you use it? python3-saml was made to validate SAMLResponses

The [Response class](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py) is able to process the SAMLResponse, and with
[OneLogin_Saml2_Utils.validate_sign](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L792) method you can validate the Signature.

**Comment by Vinod83GH** [comment]
Hi @pitbulk , I tried signing the saml assertion response using pysaml2, 
self.sec.sign_assertion("%s" % ass, id_attr='ID'). But this also gives me the <SignatureValue> with spaces. Is there anything that i am missing. If i validate against saml online tool it say same error as - 'Signature validation failed. Reference validation failed'.

Not getting any idea why its failing to validate, please help me.

------------base64 encoded saml signed response--------
PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxzYW1scDpSZXNwb25zZSB4bWxuczpzYW1scD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiB4bWxuczpkc2lnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIiB4bWxuczplbmM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jIyIgeG1sbnM6c2FtbD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgeG1sbnM6eDUwMD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb2ZpbGVzOmF0dHJpYnV0ZTpYNTAwIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9ET01BSU4tRU5USVRZL3Nzby9zYW1sL2Fjcy8iIElEPSJpZC1jYzlmMDI1Ny05MTQxLTQ0MDItYmEwOS03NGYyMTliMWJjNTciIElzc3VlSW5zdGFudD0iMjAxOS0xMS0xMlQwNToyODo0NC4zMzBaIiBWZXJzaW9uPSIyLjAiPgogICAgPHNhbWw6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij5odHRwczovL0RPTUFJTi1FTlRJVFkvc3NvL3NhbWwvPC9zYW1sOklzc3Vlcj4KICAgIDxzYW1scDpTdGF0dXM+CiAgICAgICAgPHNhbWxwOlN0YXR1c0NvZGUgVmFsdWU9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpzdGF0dXM6U3VjY2VzcyIvPgogICAgPC9zYW1scDpTdGF0dXM+CiAgICA8c2FtbDpBc3NlcnRpb24gSUQ9ImlkLTg0Yjc4NmUwLWRmNmUtNGI3ZC05M2ZjLWZmZDc4MjFjMzhhYyIgSXNzdWVJbnN0YW50PSIyMDE5LTExLTEyVDA1OjI4OjQ0LjMzMFoiIFZlcnNpb249IjIuMCI+CiAgICAgICAgPHNhbWw6SXNzdWVyIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6ZW50aXR5Ij5odHRwczovL0RPTUFJTi1FTlRJVFkvc3NvL3NhbWwvPC9zYW1sOklzc3Vlcj4KICAgICAgICA8ZHNpZzpTaWduYXR1cmU+CiAgICAgICAgICAgIDxkc2lnOlNpZ25lZEluZm8+CiAgICAgICAgICAgICAgICA8ZHNpZzpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+CiAgICAgICAgICAgICAgICA8ZHNpZzpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz4KICAgICAgICAgICAgICAgIDxkc2lnOlJlZmVyZW5jZT4KICAgICAgICAgICAgICAgICAgICA8ZHNpZzpUcmFuc2Zvcm1zPgogICAgICAgICAgICAgICAgICAgICAgICA8ZHNpZzpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPgogICAgICAgICAgICAgICAgICAgICAgICA8ZHNpZzpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz4KICAgICAgICAgICAgICAgICAgICA8L2RzaWc6VHJhbnNmb3Jtcz4KICAgICAgICAgICAgICAgICAgICA8ZHNpZzpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPgogICAgICAgICAgICAgICAgICAgIDxkc2lnOkRpZ2VzdFZhbHVlPmxDUzNCRGRoZDVheURILzV4bDUxUWlGdHp4ND08L2RzaWc6RGlnZXN0VmFsdWU+CiAgICAgICAgICAgICAgICA8L2RzaWc6UmVmZXJlbmNlPgogICAgICAgICAgICA8L2RzaWc6U2lnbmVkSW5mbz4KICAgICAgICAgICAgPGRzaWc6U2lnbmF0dXJlVmFsdWU+S2x2Q1h4VVhnWUFKbEkzRGczU0U1QndBYmdnL25ROU1waWMyUUtBcjhaSVlOMjcxMFhjVXZjUzlFTFQwN2FpNQoxeUNORTJQL1h3c2kyNGFKV0RWNmUvZWdGWDB0a0hBTlBjUXZOaG1COG1iSzFtc29vMjUxOUNXR3UyQm5VK1B3CmJYeGxGSEFRYksvQWs3Mkxpd3RCM1ZsZkVJRW5ob3V2VE5RRUVHNVRKcnkvUzR6RVhwemlEcjRhVExPQVV4RksKZW9TZENFSGRoMG1UdHJoQmdVMFU1cEgvbTh0czJHSStSNFN6V1d4RFluZk9PNEVFY2trZHFTdGN4T09oVWFyVApLUlYwNnBNZXQydk5RbXdGSWFLRW1CSTdySW9RN0Fwd1NqUkhSdmI1RUsrdUk4bWNDYnBHTWZwQ3JRRHc4emJ1CkovdzAzRFEwZU04bnFOSmZvRlhHVUE9PTwvZHNpZzpTaWduYXR1cmVWYWx1ZT4KICAgICAgICA8L2RzaWc6U2lnbmF0dXJlPgogICAgICAgIDxzYW1sOlN1YmplY3Q+CiAgICAgICAgICAgIDxzYW1sOk5hbWVJRCBGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjEuMTpuYW1laWQtZm9ybWF0OmVtYWlsQWRkcmVzcyI+TkFNRV9JRF9WQUxVRTwvc2FtbDpOYW1lSUQ+CiAgICAgICAgICAgIDxzYW1sOlN1YmplY3RDb25maXJtYXRpb24gTWV0aG9kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6Y206YmVhcmVyIj4KICAgICAgICAgICAgICAgIDxzYW1sOlN1YmplY3RDb25maXJtYXRpb25EYXRhIE5vdE9uT3JBZnRlcj0iMjAxOS0xMS0xMlQwNTozMzo0NC4zMzFaIiBSZWNpcGllbnQ9Imh0dHBzOi8vRE9NQUlOLUVOVElUWS9zc28vc2FtbC9hY3MvIi8+CiAgICAgICAgICAgIDwvc2FtbDpTdWJqZWN0Q29uZmlybWF0aW9uPgogICAgICAgIDwvc2FtbDpTdWJqZWN0PgogICAgICAgIDxzYW1sOkNvbmRpdGlvbnMgTm90QmVmb3JlPSIyMDE5LTExLTEyVDA1OjI4OjQ0LjMzMFoiIE5vdE9uT3JBZnRlcj0iMjAxOS0xMS0xMlQwNTozMzo0NC4zMzFaIj4KICAgICAgICAgICAgPHNhbWw6QXVkaWVuY2VSZXN0cmljdGlvbj4KICAgICAgICAgICAgICAgIDxzYW1sOkF1ZGllbmNlPmh0dHBzOi8vRE9NQUlOLUVOVElUWS9zc28vc2FtbC9tZXRhZGF0YS88L3NhbWw6QXVkaWVuY2U+CiAgICAgICAgICAgIDwvc2FtbDpBdWRpZW5jZVJlc3RyaWN0aW9uPgogICAgICAgIDwvc2FtbDpDb25kaXRpb25zPgogICAgICAgIDxzYW1sOkF1dGhuU3RhdGVtZW50IEF1dGhuSW5zdGFudD0iMjAxOS0xMS0xMlQwNToyODo0NC4zMzBaIiBTZXNzaW9uSW5kZXg9ImlkLTg0Yjc4NmUwLWRmNmUtNGI3ZC05M2ZjLWZmZDc4MjFjMzhhYyI+CiAgICAgICAgICAgIDxzYW1sOkF1dGhuQ29udGV4dD4KICAgICAgICAgICAgICAgIDxzYW1sOkF1dGhuQ29udGV4dENsYXNzUmVmPnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0PC9zYW1sOkF1dGhuQ29udGV4dENsYXNzUmVmPgogICAgICAgICAgICA8L3NhbWw6QXV0aG5Db250ZXh0PgogICAgICAgIDwvc2FtbDpBdXRoblN0YXRlbWVudD4KICAgICAgICA8c2FtbDpBdHRyaWJ1dGVTdGF0ZW1lbnQ+CiAgICAgICAgICAgIDxzYW1sOkF0dHJpYnV0ZSBOYW1lPSJSZWxheVN0YXRlIiBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIj4KICAgICAgICAgICAgICAgIDxzYW1sOkF0dHJpYnV0ZVZhbHVlIHhtbG5zOnhzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSIgeHNpOnR5cGU9InhzOnN0cmluZyI+aHR0cHM6Ly9ET01BSU4tREVTVElOQVRJT04vcGFnZS80MmE5Zjk0YS00M2ZjLTRiMzItOWNhMC04ZjMzMzc5NmQzNTEvPC9zYW1sOkF0dHJpYnV0ZVZhbHVlPgogICAgICAgICAgICA8L3NhbWw6QXR0cmlidXRlPgogICAgICAgIDwvc2FtbDpBdHRyaWJ1dGVTdGF0ZW1lbnQ+CiAgICA8L3NhbWw6QXNzZXJ0aW9uPgo8L3NhbWxwOlJlc3BvbnNlPgo=

--------END---------

-----base64 encoded, certificate.pem------------
LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiRENDQWxRQ0NRQ2FiSHV0ZDdaOUJqQU5CZ2txaGtpRzl3MEJBUXNGQURCNE1Rc3dDUVlEVlFRR0V3SkoKVGpFTU1Bb0dBMVVFQ0F3RFMwRlNNUXd3Q2dZRFZRUUhEQU5UUWtNeEN6QUpCZ05WQkFvTUFrbFVNUXN3Q1FZRApWUVFMREFKSlZERVZNQk1HQTFVRUF3d01kM2QzTG1sdVptOHVZMjl0TVJ3d0dnWUpLb1pJaHZjTkFRa0JGZzFwCmJtWnZRRzFoYVd3dVkyOXRNQjRYRFRFNU1URXhNekEzTURjd09Gb1hEVEl3TVRFeE1qQTNNRGN3T0Zvd2VERUwKTUFrR0ExVUVCaE1DU1U0eEREQUtCZ05WQkFnTUEwdEJVakVNTUFvR0ExVUVCd3dEVTBKRE1Rc3dDUVlEVlFRSwpEQUpKVkRFTE1Ba0dBMVVFQ3d3Q1NWUXhGVEFUQmdOVkJBTU1ESGQzZHk1cGJtWnZMbU52YlRFY01Cb0dDU3FHClNJYjNEUUVKQVJZTmFXNW1iMEJ0WVdsc0xtTnZiVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTDZnanV3YU5YUkhHMmVDazB4Y0J3MTVzaStuSmZyWHhIdkJsUEJ1N3lNUUZhMUg0ME9NWVh5NwpyLzRYakduVFlKVHdpSENZdmdoejFaUlFQR1BCQWRXUS9GS1IrV2FSWU9CUDU5cmVyeVBNK0Y5c1lGT2F4ZEFXCmRidmVYZzhvUUJ5VkpoV09kYUppMUs0b05ZMTN3WjJsSW5sY3VmMk5JK0lwQWxPMk0rTFJhR3BVenA0STJiamQKRjBoS215eEcxMFZEZlp6eG9pOEFiQWRWNVUwdFFIaFc1ODhuYTFxVFM0R0F0QTQwNVZrL2cyREdQeXRmRUtwVAplempXVXpWOU1iakh6bFZrblNZZDM4STczeU5rUUhXcXlnWDk5VFBXY05yVnBOVDNBNUxFS3hPUEdUZG1jRTJxCmtlSGp4Tk1ka0x2M0VBOWZOVCtEeEwycnpCWUhjRWNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKbEh4TmRrNFNvQ1NHQ2RMSEpCclB3MW5zdGd3bmRqODFTRHlPUDh0N1k4QlVqTXFJWW52djJObGRUVUUzZGZRTgo1QU5HTlBWd3o1VG9RcDYrdWErNnExY0dteWFoczJ6cW4vNEx3Y1ppbWpyRHFZWmhJWTV2VjdpcVVYWjlKdmJVCmUvVmZXZFRRNkdReFhqajJGb2JEU3JNN1pPNDA1ZG9SL3ZLZW1EbnRsei82d3FCUVYxSG5qb21hRGIwSmxPcUsKU2xwbEQ2aHZJYjhOc3BNeWxVaUM3eUlPVmQwazJDb0dNUi9leEhzMXo3N2gvd0hQOUo4aFppK2VuTUNyLy9ZZwpPd3dJeTFzMEc2MTJWUnZLU2swSHFXVlgzOUFHWHNHVTNGYW9MeXE1TEZLZnE0dGFQa1YycHRDUFZpdHY2VS8wCnpRWDErTGQ5N25HVnlZV0hlYUJhRlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---------end---------

**Comment by Vinod83GH** [comment]
@pitbulk any idea how can i provide cudtom namespace to saml response. currently its giving ns0, ns1, ns2 etc. using pysaml2 package and function - self.server.create_authn_response()

**Comment by Vinod83GH** [comment]
@pitbulk Finally my saml response generation is working. Thanks buddy.
Only small help from you required - 
How can i provide custom namespace to saml response. currently its giving ns0, ns1, ns2 etc. using pysaml2 package and function - self.server.create_authn_response()

**Comment by pitbulk** [comment]
I'm not a pysaml2 expert. Better ask in their repo.
