### ISSUE TITLE
Unrecognized valid SAML audience when working with Azure

### ISSUE THREAD

**Issue by josh-marshall-jax** [onelogin/python3-saml#169]
When apparently properly configured, a `OneLogin_Saml2_ValidationError` exception is raised when it should not be.  Modifying `src/onelogin/saml2/response.py:212` to `f'{sp_entity_id} is not a valid audience for this Response.  Must be one of {valid_audiences}',` changes the error to be more informative and reveals the following: `12345678-9012-3456-7890-123456789012 is not a valid audience for this Response.  Must be one of ['spn:12345678-9012-3456-7890-123456789012']`.

We are using the following configuration which appears to be consistent with AzureAD.

```
{
    "strict": True,
    "debug": True,
    "idp": {
        "entityId": "qwertyui-opas-dfgh-jklz-xcvbnmqwerty",
        "singleSignOnService": {
            "url": "https://login.microsoftonline.com/qwertyui-opas-dfgh-jklz-xcvbnmqwerty/saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP_POST",
        },
        "x509cert": "",
    },
    "sp": {
        "entityId": "12345678-9012-3456-7890-123456789012",
        "assertionConsumerService": {
            "url": f"http://localhost:5000/api/security/saml_redirect",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP_POST",
        },
    },
}
```

Now, this could be something mishandled on Azure's side, or just some small tweaks in this codebase.  I am unsure as to where the actual bug is, just that it manifests here in this way.

**Comment by josh-marshall-jax** [comment]
Related information: https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol

**Comment by pitbulk** [comment]
The Audience of a SAMLResponse MUST match the Service Provider Entity ID.

Based on your python3-saml config, the entityID is set as 
```
12345678-9012-3456-7890-123456789012
```
but in Microsoft, it seems you have registered something like:
```
spn:12345678-9012-3456-7890-123456789012
```


So you have 2 options, change Microsoft value or change the python3-saml settings SP entity Id to be  spn:12345678-9012-3456-7890-123456789012

**Comment by josh-marshall-jax** [comment]
We tried the latter to no success, and I can assure you we did not miss the former.

**Comment by pitbulk** [comment]
If you use [SAMLTracer](https://addons.mozilla.org/es/firefox/addon/saml-tracer/)  you will be able to record the SAMLResponse and see what value came inside the SAMLResponse for the Audience.

That value MUST strictly match the value at SP Entity ID.

**Comment by josh-marshall-jax** [comment]
It appears Microsoft is modifying the EntityID silently in flight.  I'll try to open a ticket and get back to this ticket tomorrow.

**Comment by josh-marshall-jax** [comment]
It appears this is a "feature".

```
Like the Issuer value, the Audience value must exactly match one of the service principal names that represents the cloud service in Azure AD. However, if the value of the Issuer element is not a URI value, the Audience value in the response is the Issuer value prefixed with spn:.
```

**Comment by josh-marshall-jax** [comment]
Close as Not a Bug.

Microsoft explicitly deviates from the SAML standard when the SP EntityID is not a URI.  The recommended course of action is to change from the default generated random number to the "Application URI".  There are no other actions which need to be taken which deviate from the standard from what I can tell.
