### ISSUE TITLE
Configuration behind an AWS load balancer?

### ISSUE THREAD

**Issue by nhill-cpi** [onelogin/python3-saml#185]
This library has been working wonderfully for me so far. I am now migrating my server behind an AWS load balancer, and I'm wondering what sp.crt and sp.key I should be using. Should these correspond to the public domain name of the site? Does the load balancer affect this? Thanks!

**Comment by pitbulk** [comment]
```
Should these correspond to the public domain name of the site?
```
No, you can see a different key/cert pair, even a self-signed cert.

```
 Does the load balancer affect this?
```
Maybe you will need to configure properly the [request](https://github.com/onelogin/python3-saml/blob/master/demo-django/demo/views.py#L17).

**Comment by nhill-cpi** [comment]
Thanks!

**Comment by odg0318** [comment]
Do you have the document to integrate with AWS ALB in detail?
I already wrote a code like the following.
```python
        result = {
            'https': 'on' if request.is_secure() else 'off',
            'http_host': request.META.get('HTTP_HOST', 'localhost'),
            'script_name': request.META['PATH_INFO'],
            'server_port': request.META.get('SERVER_PORT', 0),
            'get_data': request.GET.copy(),
            'post_data': request.POST.copy(),
            'query_string': request.META['QUERY_STRING']
        }
```

In my scenario, the flow of traffic is below.
* AWS ALB > NGINX > uwsgi > django
1. ALB - https://test.com
2. NGINX - http://x.x.x.x:9000
3. uwsgi - 127.0.0.1:9001
