### ISSUE TITLE
invalid_response error

### ISSUE THREAD

**Issue by vinothkumar1097** [onelogin/python3-saml#190]
Hi,

**Scenario:**
i have a flask web application which is deployed in my server. I've configured python3-saml in it. Its running fine with localhost configuration. But when i map ip-address my domain and try to navigate(https://rpa.vktech.net) , i'm getting  (invalid_response) after idp authentication. My domain is configured with load balancer behind proxy. Do i need to do change something on build_flask_request function ? 

Below is the xml generated in saml tracer tool
**Relay state url**
https://{idp url}/SingleSignOnService?SAMLRequest=fVNNj9owEL3vr4hyhySUj8gCJAr9QKI....Xw%3D%3D&RelayState=http%3A%2F%2Frpa.vktech.net%2Flogin&DXASubsequentAuthentication=false&DXA-force-authn=false
**Attributes received in xml **
<saml2:AttributeStatement>
            <saml2:Attribute Name="email"                           NameFormat="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">                     
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xs:string">vktech@rpa.net</saml2:AttributeValue>                                 
            </saml2:Attribute>
</saml2:AttributeStatement>

**settings.json**
{
    "strict": true,
    "debug": true,
    "sp": {
        "entityId": "https://rpa.vktech.net/metadata",
        "assertionConsumerService": {
            "url": "https://rpa.vktech.net/consume",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
            "url": "https://rpa.vktech.net/logout",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        "x509cert": "MIIC+zCCAeMC.......328pg=",
        "privateKey": "MIIEv.......yQ=="
    }
}

**advanced_settings.json**
{
  "security": {
    "authnRequestsSigned": false,
    "logoutRequestSigned": true,
    "signatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    "digestAlgorithm": "http://www.w3.org/2001/04/xmlenc#sha256"
  }
}

**Comment by pitbulk** [comment]
Have you enabled the debug mode?

What is returned by the [get_last_error_reason](https://github.com/onelogin/python3-saml/blob/master/demo-flask/index.py#L92)?

**Comment by vinothkumar1097** [comment]
**Im getting**
The response was received at http://rpa.vktech.net/consume instead of https://rpa.vktech.net/consume

**and below is my build request**
def build_saml_req():
    """ Build a request object suitable for python-saml, based on the
    flask request object."""
    req = {
        'https': 'on' if request.scheme == 'https' else 'off',
        'http_host': request.host,
        'server_port': urlparse(request.url).port,
        'script_name': request.path,
        'get_data': request.args.copy(),
        'post_data': request.form.copy(),
        'query_string': request.query_string
    }
    return req

**Comment by pitbulk** [comment]
are you behind a load balancer/proxy?

It seems request.scheme is returning 'http' instead 'https'

Or your system is served with HTTP but you registered in the IdP side, HTTPs

**Comment by vinothkumar1097** [comment]
yes Pitbulk. 
My application is behind the load balancer.
When an http request is served, load balancer automatically converts to https.

**Comment by pitbulk** [comment]
then, when building your request, force https on
```
'https': 'on'
```

**Comment by vinothkumar1097** [comment]
Thanks pitbulk. It worked.
