### ISSUE TITLE
xmlsec seems abandonded

### ISSUE THREAD

**Issue by darakian** [onelogin/python3-saml#192]
xmlsec is a dependency which seems to be abandoned. The last commit is from November of last year (2019). However the last release is from 2018. Recent releases of openssl have been causing deployment issues with xmlsec. In particular 
```
  File "/Users/jon/rescale/gits/rescale-platform-web/venv/lib/python3.7/site-packages/onelogin/saml2/auth.py", line 14, in <module>
    import xmlsec
ImportError: dlopen(/Users/jon/rescale/gits/rescale-platform-web/venv/lib/python3.7/site-packages/xmlsec.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/jon/rescale/gits/rescale-platform-web/venv/lib/python3.7/site-packages/xmlsec.cpython-37m-darwin.so
  Reason: image not found
```
has become a point of pain for my team. The fix at the moment is to switch to the 1.0.2 branch of openssl, but this isn't tenable long term.

I'm not sure how feasible it is for `python3-saml` to move away from xmlsec, but I wanted to report this issue in hope that removing the dependency is at least a conversation topic.

Repo:

**Comment by darakian** [comment]
Related to #191

**Comment by pitbulk** [comment]
An alternative could be to use [dm.xmlsec.binding](https://pypi.org/project/dm.xmlsec.binding/) that was used on python-saml which last version 2.0 was python3 compatible. But it last release also reference 2018.

Are you aware of an alternative?

**Comment by darakian** [comment]
> Are you aware of an alternative?

I am not. :(

**Comment by darakian** [comment]
@pitbulk It seems that xmlsec has a new maintainer. This issue may be resolved.

**Comment by hoefling** [comment]
A new version 1.3.7 of `xmlsec` [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.

**Comment by pitbulk** [comment]
Thanks @hoefling. Nice that you can continue the work at xmlsec.
