### ISSUE TITLE
JumpCloud SSO logout SAMLError

### ISSUE THREAD

**Issue by cahna** [onelogin/python3-saml#204]
## Summary

I am trying to setup SSO with JumpCloud as the identity provider for a flask app/api service provider. Login is working, but logout does not (using code from the Flask example with minor changes). 

I am learning SAML as I go, and I apologize if this should not be asked here. I have been in contact with JC support several times, and am current awaiting escalation to an engineer. Hoping someone here may have done this before or may have some insight into the correct settings needed.

## Expected behavior

- Click logout: start request to `/slo`
- `/slo` redirects to JumpCloud with `samlp:SamlLogoutRequest`
- JumpCloud redirects to `/sls`
- `/sls` endpoint clears user session and redirects appropriately

## Current behavior

Upon logout, the Flask handler for `/slo` is invoked, and a redirect to JumpCloud's logout url is returned (`https://sso.jumpcloud.com/saml2/my-app/slo`). Here is the SAMLRequest from firefox debug extension:

```xml
<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="ONELOGIN_402...ddce"
                     Version="2.0"
                     IssueInstant="2020-07-24T04:40:19Z"
                     Destination="https://sso.jumpcloud.com/saml2/my-app/slo"
                     >
    <saml:Issuer>http://my-app.localhost:5000</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">myemail@mydomain.com</saml:NameID>
    <samlp:SessionIndex>8593617e-a517-4849-9426-f28f4963423c</samlp:SessionIndex>
</samlp:LogoutRequest>
```

I am not redirected back to my `/sls` endpoint, and am shown this error on a JC page:

![jc-saml-logout-error](https://user-images.githubusercontent.com/1045603/88360560-fd499580-cd2a-11ea-95dc-15c6acd26a23.png)

### SP metadata
```xml
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" validUntil="2020-07-26T04:28:10Z" cacheDuration="PT604800S" entityID="http://my-app.localhost:5000">
  <md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>...</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://my-app.localhost:5000/saml/sls?store=my-saml"/>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://my-app.localhost:5000/saml/acs?store=my-saml" index="1"/>
  </md:SPSSODescriptor>
  <md:Organization>
    <md:OrganizationName xml:lang="en-US">MyOrg</md:OrganizationName>
    <md:OrganizationDisplayName xml:lang="en-US">My Org</md:OrganizationDisplayName>
    <md:OrganizationURL xml:lang="en-US">http://my-app.localhost:5000</md:OrganizationURL>
  </md:Organization>
  <md:ContactPerson contactType="technical">
      ...
  </md:ContactPerson>
</md:EntityDescriptor>
```

### Idp metadata
```xml
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://sso.jumpcloud.com/saml2/my-app">
  <md:IDPSSODescriptor WantAuthnRequestsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>...</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </md:KeyDescriptor>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://sso.jumpcloud.com/saml2/my-app"/>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://sso.jumpcloud.com/saml2/my-app"/>
  </md:IDPSSODescriptor>
</md:EntityDescriptor>
```

### Idp settings
```json
  "idp": {
    "entityId": "https://sso.jumpcloud.com/saml2/my-app",
    "singleSignOnService": {
      "url": "https://sso.jumpcloud.com/saml2/my-app",
      "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "singleLogoutService": {
      "url": "https://sso.jumpcloud.com/saml2/my-app/slo",
      "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "x509cert": "..."
  }
```
For `idp.singleLogoutService.url`, I have tried:
- `https://sso.jumpcloud.com/saml2/my-app`
- `https://sso.jumpcloud.com/saml2/my-app/slo`
- `https://sso.jumpcloud.com/saml2/my-app/sls`
Note: As an experiment, I was able to get JumpCloud SAML working as an Auth0 connection using the `/slo` url. I am not sure if this is correct for `python3-saml` config. Waiting to hear from JC engineer about this.

I have also tried permutations of `HTTP-Post` for each binding value paired with each url, above.

### Security
```json
  "security": {
    "nameIdEncrypted": false,
    "authnRequestsSigned": true,
    "logoutRequestSigned": true,
    "logoutResponseSigned": true,
    "signMetadata": false,
    "wantMessagesSigned": false,
    "wantAssertionsSigned": true,
    "wantNameId": true,
    "wantNameIdEncrypted": false,
    "wantAssertionsEncrypted": false,
    "wantAttributeStatement": true,
    "signatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
    "digestAlgorithm": "http://www.w3.org/2001/04/xmlenc#sha256"
  }
```
Any suggestions on how these values should look?

## Changes to example code
- I split the single `/login` route into `/saml/login`, `/saml/acs`, `/saml/sso`, etc
- The example handler for `/login?sls` is checking for `LogoutRequestID` in `Flask.session`. That value isn't being set anywhere, so **it appeared that the example handler for `/login?slo` was missing**:
  ```python
  session["LogoutRequestID"] = auth.get_last_request_id()
  ```
- settings are provided as a `dict` instead of from files
- Otherwise my code and the example are the same

**Comment by ljudva** [comment]
Hi there, 

I'm getting 
![image](https://user-images.githubusercontent.com/36252744/88616044-b4e0fd80-d0c5-11ea-9dac-24066690cae3.png)

even on /acs 
Plus, after login, I see "You have not been given access to any SSO applications by your administrator. " on JC Console. Bit I did give access.
Not quite sure how you managed to make it to work tho. When you say "I split the single /login route into /saml/login, /saml/acs, /saml/sso, etc" - what exactly do I need to do? Running the same as /saml 

Mind you, one-login SLO definitely works well with ie Azure SAML.

Cheers

**Comment by ljudva** [comment]
Ignore above, all good now, user error ;)

**As I see it JC has no SLO bindings...**

**Comment by cahna** [comment]
It seems you are correct. JumpCloud support sent me this:
```
I have checked with our Engineering team and they have confirmed that 
unfortunately, Single Logout Service is not supported by JumpCloud at 
the moment. Furthermore, for SLO to be successfully implemented, it 
has to be supported on both the IDP and SP side. As the actual SSO is 
using AUTHO and that has SLO available, this could be the reason that 
SLO is working on this.
```
Closing
