### ISSUE TITLE
Spurious sp_acs_url_invalid with "local" addresses

### ISSUE THREAD

**Issue by akx** [onelogin/python3-saml#207]
When an SP is configured with a DNS address that has no dots in it and isn't `localhost`, it doesn't pass the URL validity check. Case in point, as generated when running tests in Django:

```
{'assertionConsumerService': {'url': 'http://testserver/accounts/saml/acs/0173dd64-d5e3-289a-922f-6fbba01660ee/', ...}}
```

I don't see a very good reason to disallow addresses such as that.

**Comment by pitbulk** [comment]
Isn't possible to set a hostname with dots in such Django running test?

**Comment by akx** [comment]
The default is hard-coded at https://github.com/django/django/blob/3a6fa1d962ad9bd5678290bc22dd35bff13eb1f5/django/test/client.py#L344
so you'd have to either

* remember to (e.g.) `client.get('foo', SERVER_NAME='totally.a.dotted.fake.name')` for every request that involves `onelogin.saml`
* or subclass the `RequestFactory` or `Client`, which is nontrivial if you're using e.g. pytest-django fixtures.

The real question is that is the `validate_url` function really sane... https://github.com/onelogin/python3-saml/blob/6f8ca9c1f628db3a818312e678d5c2c108efbe9c/src/onelogin/saml2/settings.py#L32-L59

**Comment by pitbulk** [comment]
https://github.com/onelogin/python3-saml/commit/a1e1f8b4d0fa4cd17467446f5cbe72dc1fc80bd8

**Comment by melgart** [comment]
I know this is years late, but for anyone getting stuck on this problem using the unit test client, you can easily override the server name to anything you want in your `.get()` calls like this below, which fixed the problem identified by the OP: 

```
response = self.c.get('/emails/html/upload', SERVER_NAME="mydomain.com")
```

source: https://stackoverflow.com/a/6291428
