### ISSUE TITLE
Only configuring/implementing assertion consumer service endpoint

### ISSUE THREAD

**Issue by DrPyser** [onelogin/python3-saml#209]
Hi!

I'm working on integrating SAML SSO into our app for our enterprise login.
I was looking to use a `shibboleth` SP server to deal with the SSO login initiation, and have a separate assertion consumer service endpoint implemented using this library in our custom authentication service.

Would it be possible to use this library in this way, to only handle SAML response from the IdP without the auth request originating from the same app? 
If so, what would be required configuration-wise? 
Do I still have to specify the `idp.singleSignOnService` and `idp.singleLogoutService` options, even if they are not useful in my case(since I want to implement SP-initiated SSO)?

Thanks!

**Comment by pitbulk** [comment]
You can use the SAMLResponse class to just process the SAMLResponse, but yes you need to provide the SAML settings because the SAMLResonse will be validated against it.
