### ISSUE TITLE
Hostname in "Destination" field is treated as case-sensitive when verifying responses

### ISSUE THREAD

**Issue by afittkau** [onelogin/python3-saml#210]
According to SAML 2.0 specs, the _Destination_ field in a SAML message must be verified so that it matches the location in which the message was received. The present implementation does a simple .startswith(current_url) as can be seen [here ](https://github.com/afittkau/python3-saml/blob/589425d1fbd2161ce2a566dfcb92835a221a3541/src/onelogin/saml2/response.py#L194)

The SAML 2.0 specs state: 

> If the message is signed, the Destination XML attribute in the root SAML element of the protocolmessage MUST contain the URL to which the sender has instructed the user agent to deliver themessage. The recipient MUST then verify that the value matches the location at which the message hasbeen received.

This creates one major and one minor problem: 

- Hostnames in URL must be treated as case-insensitive - as required by URI / URL RFCs - while the rest of the URL is case-sensitive. This also holds true for IDNs as hostnames. Checking with a simple call to _.startswith()_ is case-sensitive in all cases and might cause trouble in environments where Hostnames are sometimes given in camelcase to improve readability.
- A check with _.startswith_ will ignore arbitrary additional URL parts after the _current_url_ has ended, which breaks the SAML 2.0 standard requirement quoted above. 

I can provide a pull request in a couple days to add a more sophisticated URL-equality checking to the library.

**Comment by pitbulk** [comment]
Implemented here:
https://github.com/onelogin/python3-saml/commit/949425fd81250fff588075aaa704ff2f92168dfd
