### ISSUE TITLE
Can't find out how to give more data on setting.json

### ISSUE THREAD

**Issue by arthuravila26** [onelogin/python3-saml#211]
G'day everyone!

I'm trying to make a SAML auth in my company's API but I've got a couple of doubts and coudn't find a example that can help me using Python and Flask.

My company sent to me some informations that I should send to them for make the authentication and the certificate. The informations are:

Assertion Consumer Service URL
Service Provider Logout URL
SP Certificate:
Sign Assertion: Assertion or Response or BOTH
Signature Algorithm: RSA-SHA1 or RSA-SHA256
Digest Method: SHA1 or SHA256
SAML Binding: POST or Redirect
Audience
Encrypt Assertion: yes or no
I already found the Signature Algorithm and Digest Method on advanced_setting.json on Flask example. But, Sign Assertion, Audience and Encrypt Assertion I didn't find anywhere. As it's hard to find example for saml with Python, I can't find any clue for how to give it to my company and authenticate it right and receive the right response.

If anyone could help with a example for how to pass it on the setting.json I would be very glad!

**Comment by pitbulk** [comment]
` Sign Assertion: Assertion or Response or BOTH`
This is a Settings for the IdP, the SP only can sign Responses and it is managed by:
- authnRequestsSigned
- logoutRequestSigned
- logoutResponseSigned

If at the SP you want to require signed messages or signed assertions use:  wantMessagesSigned and wantAssertionsSigned


Audience is who gonna receive the SAML Message. In case of Messages generated by an IdP, the Audience is the Entity Id of the SP. In case of Messages generated by the SP, the Audience is the IdP Entity ID.

`Encrypt Assertion`
Aply only to the IdP, SP does not generate asserition, but you can require encrypted assertion with wantAssertionsEncrypted

**Comment by arthuravila26** [comment]
Thanks mate! It worked fine for me!! =D
