### ISSUE TITLE
Support key rollover with a new certificate and a new private key

### ISSUE THREAD

**Issue by DennisNerush** [onelogin/python3-saml#216]
After reading through the docs and the PRs it seems that the current implementation supports have `x509certNew` for a silent rollover. But what happens if I have a new private key that needs to be switched along with the new certificate?
Is there an option to define both `x509certNew` and `privateKey` new?

**Comment by pitbulk** [comment]
privateKey don't need to be provided to the IdP, so we don't need to define it for the rollout.
