### ISSUE TITLE
Host Header doesn't match Destination field in Assert due to capitalization

### ISSUE THREAD

**Issue by tbloomer4** [onelogin/python3-saml#226]
Hello,

Upon integrating with a domain that has capitalization, SP-initiated SAML SSO fails with the following error:
`The response was received at https://domain/ instead of https://Domain/`

This originates from the check here:
https://github.com/onelogin/python3-saml/blob/589425d1fbd2161ce2a566dfcb92835a221a3541/src/onelogin/saml2/response.py#L194

`current_url` is derived from the http host header here:
https://github.com/onelogin/python-saml/blob/082dda831334961991ca0e3cb6b274350fd0c7a2/src/onelogin/saml2/utils.py#L330

However, RFC dictates that domain name (at least those resolved via dns) are case-insensitive (https://tools.ietf.org/html/rfc4343). As a result, when the SAML Assertion was returned to our ACS URL, the host http header was "domain", instead of "Domain". This lead to the error above. 

My suggestion is making that comparison case-insensitive (at least for the host portion, as I believe that the path _is_ case-sensitive)

Please let me know what you think! Thanks!

**Comment by pitbulk** [comment]
Ok, we could implement something like:
https://github.com/onelogin/ruby-saml/blob/17fce0a6caa6282ebd51c6276d3a7b91138b8d24/lib/onelogin/ruby-saml/utils.rb#L284

Meanwhile, you construct the [request](https://github.com/onelogin/python3-saml/blob/master/demo-django/demo/views.py#L17) which is used by the ACS endpoint, so you could provide to such request the value it expects.

**Comment by tbloomer4** [comment]
thanks! Will do!
