### ISSUE TITLE
Dependency on defusedxml

### ISSUE THREAD

**Issue by cdrx** [onelogin/python3-saml#233]
Can the dependency on defusedxml be dropped? There only use of this library is a few exceptions imported in `xmlparser.py`:

```
from defusedxml.lxml import DTDForbidden, EntitiesForbidden, NotSupportedError
```

I assume these are here for backwards compatibility. Would you accept a PR making these conditional on `defusedxml` being installed?

**Comment by eMerzh** [comment]
good idea, but i think you can look for insights here

https://github.com/onelogin/python3-saml/issues/159

**Comment by pitbulk** [comment]
I agree we could "adopt" the parts we need from defusedxml

python-saml [uses it](https://github.com/onelogin/python-saml/search?q=defusedxml) for protecting minidom, but we are not using it here, so happy if we define those DTDForbidden, EntitiesForbidden, NotSupportedError classes at xmlparser.py

Can you create the PR?
