### ISSUE TITLE
Wrong destination URL for SP initiated Single Logout

### ISSUE THREAD

**Issue by nltommynl** [onelogin/python3-saml#234]
Hi,

In 9fdb11d (which is included in v1.10.0), in addition to logout_response.py, logout_request.py has also been modified. This is incorrect and only the logout_response.py should point to a response URL. Now all _logoutRequest_ and _logoutResponse_ messages are sent to the slo response URL.

src/onelogin/saml2/logout_request.py:

`'single_logout_url': self.__settings.get_idp_slo_response_url(),`

Should be

`'single_logout_url': self.__settings.get_idp_slo_url(),`

**Comment by nltommynl** [comment]
I made a [PR](https://github.com/onelogin/python3-saml/pull/235) for this issue. @pitbulk do you see an opportunity to review/merge these?

**Comment by pitbulk** [comment]
Merged
