### ISSUE TITLE
invalid_logout_response_signature Azure AD as IDP

### ISSUE THREAD

**Issue by starboywizzy521** [onelogin/python3-saml#252]
Hi Everyone ! I really appreciate your work to make this library. 
I have deployed the flask-demo of python3-saml library and configured SSO with Azure AD as Identity Provider. The Single SignOn is working perfectly but the Logout is not working.
![logout not wiorking](https://user-images.githubusercontent.com/40290563/110142980-075e6700-7dd7-11eb-9f4e-b3fcb49e73ff.PNG)

There are my setting Azure Side :
![azure side](https://user-images.githubusercontent.com/40290563/110143730-d92d5700-7dd7-11eb-8435-c74a6ad71456.PNG)

There my Service Provider (flask-demo) settings:

`{
    "strict": true,
    "debug": true,
    "sp": {
        "entityId": "https://zaz.xxxxxxxx.com/metadata",
        "assertionConsumerService": {
            "url": "https://zaz.xxxxxxx.com/?acs",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
            "url": "https://zaz.xxxxxxxx.com/?sls",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAdress",
        "x509cert": "xxxxxxxxxxxxxxxx",
        "privateKey": "xxxxxxxxxxxxxxxxxx"
    },
    "idp": {
        "entityId": "https://sts.windows.net/c048c2a6-d390-49cc-af66-6e0b1d805cbf/",
        "singleSignOnService": {
            "url": "https://login.microsoftonline.com/c048c2a6-d390-49cc-af66-6e0b1d805cbf/saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "singleLogoutService": {
            "url": "https://login.microsoftonline.com/c048c2a6-d390-49cc-af66-6e0b1d805cbf/saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "x509cert": "xxxxxxxxxxxxxxxxxx"
    }
}
`

This is my SAML:LogoutRequest sent by my SP (flask-demo) to my IDP (Azure AD):

`<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="ONELOGIN_54f110ddfb835b6e78176fd00862fa7035cde567"
                     Version="2.0"
                     IssueInstant="2021-03-05T11:32:58Z"
                     Destination="https://login.microsoftonline.com/c048c2a6-d390-49cc-af66-6e0b1d805cbf/saml2"
                     >
    <saml:Issuer>https://zaz.xxxxxxxxxx.com/metadata</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">xxxxx@xxxxxxx.com</saml:NameID>
    <samlp:SessionIndex>_26bb6821-f5e9-47e3-9c1d-be2317bd7500</samlp:SessionIndex>
</samlp:LogoutRequest>` 

This is my SAML:LogoutResponse sent by my  IDP (Azure AD) to mySP (flask-demo) :

![samLogoutResponse](https://user-images.githubusercontent.com/40290563/110146210-9620b300-7dda-11eb-898c-f20c7a817415.PNG)

This one is needed to be validate my SP to complete the logout but it isn't working. Please help me !

**Comment by pitbulk** [comment]
Try enabling the 'lowercase_urlencoding' setting
https://github.com/onelogin/python3-saml/blob/589425d1fbd2161ce2a566dfcb92835a221a3541/demo-flask/index.py#L32

**Comment by starboywizzy521** [comment]
OMG ! I can't believe my eyes, it's working. Yooooo you're the  MAN. Thanks thanks thanks !
![samLogoutResponseWorking](https://user-images.githubusercontent.com/40290563/110316050-740d7780-800a-11eb-9c57-f96235a5f5ad.PNG)

But i have a little problem (it's not really one).  When i hit the logout button, it also log me out of my office.com session. Is it possible to manage to just get logout of the flask app only and keep my microsoft session active ? How can i achieve that please ?

**Comment by pitbulk** [comment]
Don't think so, SLO means you get logged out from any connected Service Provider, if office365 is connected to Azure AD... then it will log out
