### ISSUE TITLE
Embed SAML Verification Signature (the SP Signing Public Cert) to the the AuthnRequest

### ISSUE THREAD

**Issue by rebornjoe** [onelogin/python3-saml#258]
I've tried to look for any references to do this but thought that it might not be possible with the library. Some Identity Providers require that the signing certificate be embedded in the AuthnRequest in order for the IdP to verify the request as well as match the subject DN and confirm if the certificate was signed by a CA.  Is there any documentation on how to achieve this?  Thank you

**Comment by pitbulk** [comment]
HTTP-POST binding is not supported for the AuthNRequest.
