### ISSUE TITLE
jupyterhub support

### ISSUE THREAD

**Issue by richiverse** [onelogin/python3-saml#28]
Is this on the roadmap or is there an example of this?

**Comment by pitbulk** [comment]
This is a SAML toolkit, so implement an Authenticator for jupyterhub can't be in the Roadmap.

It seems that there is no SAML support at jupyterhub based on:
https://groups.google.com/forum/#!topic/jupyter/5OmbZfjCerM

I have no idea of jupyterhub, but if some contributor want to implement it, I can help solving any SAML doubt.

**Comment by pitbulk** [comment]
@spendyala Find my mail in my profile. Send me there the details.
