### ISSUE TITLE
Depending on a yanked `lxml==4.7.0` in `setup.py` causes failed builds.

### ISSUE THREAD

**Issue by vkomarov-r7** [onelogin/python3-saml#300]
In the latest released version of `python3-saml`, it looks like [this commit](https://github.com/onelogin/python3-saml/commit/a55cc9a379da03eff9f96a886f6164fd0792a62e) pinned the version of `lxml` to `4.7.0`. This version of `lxml` [has since been yanked](https://pypi.org/project/lxml/4.7.0/) due to not having the appropriate header files included in the wheels, breaking on the majority of platforms.

If possible, please either revert this change or use a more flexible requirement string that specifically excludes versions that do not work (e.g. `lxml<4.7.0`).

**Comment by bzvestey** [comment]
This should be fixed in the latest version of python2-saml, please let us know if this issue continues.
