### ISSUE TITLE
Signatures are not verified by default, even in 'strict' mode

### ISSUE THREAD

**Issue by jgehrcke** [onelogin/python3-saml#33]
That's the same for python3-saml and python-saml, so please refer to
https://github.com/onelogin/python-saml/issues/168

**Comment by pitbulk** [comment]
They are verified, and a ["No Signature found. SAML Response rejected"](https://github.com/onelogin/python3-saml/blob/master/tests/src/OneLogin/saml2_tests/response_test.py#L709) is added to the errors.
