### ISSUE TITLE
Impossible to catch exceptions that aren't OneLogin_Saml2_Error

### ISSUE THREAD

**Issue by nickw444** [onelogin/python3-saml#40]
I'm having an issue where the library is throwing an `Exception` that is of the base `Exception` type. I want to handle errors gracefully that occur within this library, but don't really want to catch every single exception that occurs. 

Is there a particular reason this library uses `OneLogin_Saml2_Error` in some places, but others, like in https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L301, just use `Exception`? Would it be possible to introduce a new class of `Exception` which is used in place of these so that they can be caught more easily without catching all `Exception` types.

Cheers

**Comment by pitbulk** [comment]
Right now I think that OneLogin_Saml2_Error is used to catch errors related to the SAML settings or when SAML messages not detected (bad SSO/SLO flow).

Im agree that we may improve the way we take care of exceptions and help to the dev on the debug process.

**Comment by nickw444** [comment]
Would you be willing to accept a PR with changes to a more specific exception class?

**Comment by pitbulk** [comment]
Something like OneLogin_Saml2_ValidationError ?

**Comment by nickw444** [comment]
After looking into errors.py, it seems the OneLogin_Saml2_Error is pretty multi-purpose. 

Thoughts on whether I should add a new error code, and use it, or use a totally new exception class?

https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/errors.py#L32

**Comment by pitbulk** [comment]
You can see that those error codes are related to settings or anormal SAML flow.

I think we can create a similar OneLogin_Saml2_ValidationError with codes that describes what validation failed, then we get a more complete error handle. What do you think?

**Comment by nickw444** [comment]
Sounds good to me!

**Comment by pitbulk** [comment]
@nickw444 Do you have more custom ValidationException to submit? If not I will take care of this commit and implement it.

**Comment by pitbulk** [comment]
I'm taking care of it.

**Comment by nickw444** [comment]
Thanks
