### ISSUE TITLE
fingerprint setting doesn't accept dotted format

### ISSUE THREAD

**Issue by cperrin88** [onelogin/python3-saml#44]
When using a fingerprint in the format

    EA:67:6B:1D:AA:F3:A6:08:85:48:91:71:73:5F:0A:37:35:AD:E2:3B

certificate validation fails. If the `:` characters are removed it works as expected.

**Comment by pitbulk** [comment]
Thanks for catch that.

The [format_finger_print](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L543) method should be applied.

Can you modify at the [response.py](https://github.com/onelogin/python3-saml/blob/ce0d716b086cc65b8592f1a92947831d0d7716dd/src/onelogin/saml2/response.py#L276) file
```
fingerprint = idp_data.get('certFingerprint', None)
```
by
```
fingerprint = idp_data.get('certFingerprint', None)
if fingerprint:
    fingerprint = OneLogin_Saml2_Utils.format_finger_print(fingerprint)
```

and check if that solved the issue?

If it solved, a PR that includes that change + tests are welcome ;)

**Comment by cperrin88** [comment]
I'll look into that

**Comment by pitbulk** [comment]
Merged the PR, Thanks for collaborate.
