### ISSUE TITLE
IDP in python3-saml

### ISSUE THREAD

**Issue by muke5hy** [onelogin/python3-saml#48]
Hi, Can I create IDP by using python3-saml. I read the documentation and could not found any related page.

**Comment by pitbulk** [comment]
python3-saml only covers the Service Provider part.

If you need to implement an Identity Provider using Python, review those projects:
- https://github.com/mobify/dj-saml-idp
- https://github.com/rohe/pysaml2/
- https://dev.entrouvert.org//projects/authentic/
