### ISSUE TITLE
Flask debug=True causes TypeError with xmlsec

### ISSUE THREAD

**Issue by nwbreneman** [onelogin/python3-saml#5]
Running a Flask app with debug=True (``app.run(debug=True)``) returns a TypeError when attempting to enable debugging for xmlsec:

``xmlsec.enable_debug_trace(debug)``

e.g. in https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L557

Using a 0 or 1 instead of True/False works correctly.

I am using xmlsec 0.3.3.

**Comment by bgaifullin** [comment]
Hi.
Thank you for issue.
Could you post a bug to xmlsec project[1]

[1] https://github.com/mehcode/python-xmlsec
