### ISSUE TITLE
csrf django issue

### ISSUE THREAD

**Issue by danielkalenda** [onelogin/python3-saml#51]
We have csrf middelware enabeled.
It appears it's not happy with the saml request.

Error:
CSRF token missing or incorrect is the error in django

How can this be fixed?

**Comment by pitbulk** [comment]
You will need to use the [@csrf_exempt](https://docs.djangoproject.com/en/1.10/ref/csrf/) decorator on the Assertion consumer service endpoint.

SAML has its own mechanism to verify that the info received is ok, so you don't need that extra csrf protection.

**Comment by danielkalenda** [comment]
thanks i just tried with that and get 

Errors:
invalid_response

The Debug is on in the settings.json, but i don't get more information.

I have a custom user model is that the problem?
In the settings.json i changed nameId to emailAddress. 
The Email exists in my Database and the one login db.

I pretty much did the Tutorial:
https://developers.onelogin.com/saml/python

**Comment by pitbulk** [comment]
In order to get the reason for the error, you can use the [get_last_error_reason](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/auth.py#L251) method.
