### ISSUE TITLE
lxml ValueError exception in process_slo()

### ISSUE THREAD

**Issue by Ratler** [onelogin/python3-saml#60]
SP is using python3-saml version 1.2.6
IdP is Shibboleth Identity Provider version 3.3.0

When calling `process_slo()` the following exception is thrown:

```  File "/opt/env/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 137, in process_slo
    logout_response = OneLogin_Saml2_Logout_Response(self.__settings, get_data['SAMLResponse'])
  File "/opt/env/lib/python3.6/site-packages/onelogin/saml2/logout_response.py", line 41, in __init__
    self.document = OneLogin_Saml2_XML.to_etree(self.__logout_response)
  File "/opt/env/lib/python3.6/site-packages/onelogin/saml2/xml_utils.py", line 66, in to_etree
    return OneLogin_Saml2_XML._parse_etree(xml)
  File "/opt/env/lib/python3.6/site-packages/defusedxml/lxml.py", line 143, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79609)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119069)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
As the exception says the SLO SAMLResponse contain an encoding tag, i.e. `<?xml version="1.0" encoding="UTF-8"?>` which isn't allowed when feeding etree.fromstring with a unicode string.

Not sure what the best solution would be in this case, but changing `compat.to_string()` 
 to `compat.to_bytes()` seem to work:
https://github.com/onelogin/python3-saml/blob/16cd67c0efa329ac016abdb8471cb0d654a68825/src/onelogin/saml2/logout_response.py#L40

**Comment by pitbulk** [comment]
If I change to_string by to_bytes, tests executed in python2 fail.

**Comment by Ratler** [comment]
@pitbulk I noticed that a couple of tests failed so I changed it to this instead:

```
diff --git a/src/onelogin/saml2/logout_response.py b/src/onelogin/saml2/logout_response.py
index 7a27af8..3d1d5e4 100644
--- a/src/onelogin/saml2/logout_response.py
+++ b/src/onelogin/saml2/logout_response.py
@@ -39,7 +39,7 @@ class OneLogin_Saml2_Logout_Response(object):
 
         if response is not None:
             self.__logout_response = compat.to_string(OneLogin_Saml2_Utils.decode_base64_and_inflate(response))
-            self.document = OneLogin_Saml2_XML.to_etree(self.__logout_response)
+            self.document = OneLogin_Saml2_XML.to_etree(compat.to_bytes(self.__logout_response))
             self.id = self.document.get('ID', None)
 
     def get_issuer(self):

```

All tests pass and it also works in my production environment with Shibboleth 3.3.x.

**Comment by kitab15** [comment]
Same problem here, are you thinking to fix it soon @pitbulk? 
It would be great! Thanks!

**Comment by pitbulk** [comment]
Yes I need to fix that and generate a new release. I hope to be able to do it soon (this or next week)

**Comment by EvanPurkhiser** [comment]
Looks like the parser also doesn't like the encoding declaration. Since it passes in unicode strings here: https://github.com/onelogin/python3-saml/blob/b3968330d5c39dbc1c805b4863dd183870d5f43c/src/onelogin/saml2/idp_metadata_parser.py#L127

Any plans to fix that?

**Comment by kitab15** [comment]
Any news about this issue @pitbulk?

**Comment by pitbulk** [comment]
Have you tested if SLO IdP initiaited, where a LogoutRequest is sent to the SP also experience this issue?

**Comment by kitab15** [comment]
No, only SLO SP-initiated.

**Comment by pitbulk** [comment]
Does #77 fix the issue?
Can you guys provide tests with examples of LogoutResponse and IdP Metadata XMLs so we prevent to revert this fix?

**Comment by kitab15** [comment]
#77 fix the issue!! 
I'll try to develop some test, but I'm not sure when.

**Comment by pitbulk** [comment]
@kitab15 if you don't have time, simple send me the XML examples and I can build unit test myself.

**Comment by kitab15** [comment]
I think that the examples you are testing right now could be fine, if you add the encoding tag at the beginning of the XMLs files.
`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by kitab15** [comment]
Hi @pitbulk , I have tested SLO IdP-initiaited and just like was described in #81 , the problem is also there. 

Replacing in` logout_request.py:115`

`self.__logout_request = compat.to_string(logout_request)`

with 

`self.__logout_request = logout_request`

works for me. 

I couldn't help you with some tests yet, but I will do it as soon as I can.

**Comment by pitbulk** [comment]
@cbouvier15 @Ratler can you guys check if #127 solves your issue?
