### ISSUE TITLE
How to fix destination validation?

### ISSUE THREAD

**Issue by AlexandrPy** [onelogin/python3-saml#61]
Hello!

I am using your python3-saml module and I have some misunderstanding with ports, when implementing SAML2 SSO for our app. The validation of the destination fails because there is a validation of the `current_url` [here](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L181) and it constructs that url [in utils](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L288). But for some reason the port in the `current_url` is not default, but 8080.

I understand, that this port is extracted from our side, but this does not have much sense, since the request itself is made on the default url `https://example.com/sso/saml2/?acs`, but our IDP must have ACS url with port 8080 in his SAMLResponse `https://example.com:8080/sso/saml2/?acs` to be able to pass this validation.

So, I have a misunderstanding here. What exactly this validation checks? Is it possible to disable it and do I increase the security risk in this case?

Thank you.

**Comment by pitbulk** [comment]
You may not disable any security check.

1. You may verify that the SP's metadata registered on the IdP is right.
2. current_url is built based on the data that is provided in the [request](https://github.com/onelogin/python3-saml#the-request), so review what values you set there.

**Comment by AlexandrPy** [comment]
Thank you. This is very useful.
