### ISSUE TITLE
Parsing Multiple Signing Certificates from IDP Metadata fails

### ISSUE THREAD

**Issue by bmorgan21** [onelogin/python3-saml#64]
https://github.com/onelogin/python3-saml/blob/34d22e005d21b7888d02588021bdf5a92391607b/src/onelogin/saml2/idp_metadata_parser.py#L203

I believe the first check `len(certs) == 1` is not correct.  In the case where there are multiple signing certs, but no encryption certs, it throws away signing certs and only keeps the first one.  This is not correct behavior.

**Comment by pitbulk** [comment]
Can you provide a PR?

**Comment by bmorgan21** [comment]
I will put one up shortly.

**Comment by pitbulk** [comment]
ty

**Comment by bmorgan21** [comment]
https://github.com/onelogin/python3-saml/pull/65

**Comment by pitbulk** [comment]
Merged
