### ISSUE TITLE
Redirection URL is not always returned by `auth.process_slo`

### ISSUE THREAD

**Issue by AJdeMooij** [onelogin/python3-saml#69]
In `auth.py`, the docs for the function `process_slo` state the following:
 :returns: Redirection url

This is not the case in the processing of the `SAMLResponse` (lhttps://github.com/onelogin/python3-saml/blame/master/src/onelogin/saml2/auth.py#L143) part of the function (although it is in the `SAMLRequest` part, https://github.com/onelogin/python3-saml/blame/master/src/onelogin/saml2/auth.py#L159). This means that a RelayState can only be provided in a IdP-initiated logout.

In the readme (under *Initiate SLO*) the following example code is provided:
```python
target_url = 'https://example.com'
auth.logout(return_to=target_url)
```
This suggests that the RelayState is actually an important part of the Service Provider initiated SLO.

An easy solution would be to add the following code at line 158:
```python
if 'RelayState' in self.__request_data['get_data']:
    return self.redirect_to()
```

I would create a pull request with these changes myself, but I am not entirely sure if this is intended behaviour or if this change should indeed be made.

**Comment by pitbulk** [comment]
When we processing a LogoutResponse, we don't need to generate any LogoutRequest/LogoutResponse, that is why we don't return anything in that case, and just remove session if the right paramter was provided.

RelayState is a SAML parameter, that can be used to notify the SAML Entity where to redirect after process a SAML message.

You may use the [redirect_to](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/auth.py#L195) mthod

url = auth.process_url()
auth.redirect_to(url)

This will redirect to the url if the process_url returned anything, or to the relayState value...
