### ISSUE TITLE
There is no AttributeStatement on the Response

### ISSUE THREAD

**Issue by rocketrip-al** [onelogin/python3-saml#7]
Is it necessary to require an Attribute Statement in the SAML Response?  

When setting up a SAML app in Okta (the Identity Provider in this case), the form says that configuring Attribute Statements is optional.  That leaves us open to the above error though.  I've also run into this issue when using Centrify as an IdP.

So would it be possible to remove this check and what would be the implications of that?  Thanks for the help!

Reference:  Check out the Attribute Statements section in step 7
http://developer.okta.com/docs/guides/setting_up_a_saml_application_in_okta.html

**Comment by pitbulk** [comment]
We fixed that on python-saml:
https://github.com/onelogin/python-saml/commit/53f6bf4baf42c54cc60a306d5683a9700467f91a

I will fix that on python3-saml too.

**Comment by rocketrip-al** [comment]
Thanks!

**Comment by GianSilvCRI** [comment]
still getting this error on python3-saml 1.4.1.

**Comment by GianSilvCRI** [comment]
Thanks, my bad

**Comment by melvyn-apryl** [comment]
For people wanting to know the implications: you need a custom backend as the default backend will [look for the `uid` in the attribute statement](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/response.py#L588) and thus fail.
