### ISSUE TITLE
Undocumented "req" Parameters

### ISSUE THREAD

**Issue by cjduffett** [onelogin/python3-saml#71]
There are 3 undocumented parameters that could potentially be passed as part the `req` dict used to initialize the `OneLogin_Saml2_Auth` client. These are:

1. `https` - Unsuspecting users could potentially see validation of responses fail if they're received over HTTPS and the user didn't explicitly configure that (since the default is `http`)

2. `lowercase_urlencoding` -  There's a short comment in [utils.py](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L70) describing why this is an option, but users may not be aware of this option if they're using ADFS

3. `request_uri` - Used in [utils.py#L339-L380](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py) to build self URLs

In the documentation users should at least be aware of these options, what they're for, and when they should be used. Ideally no one should have to read your source code to use your client. 🙂

**Comment by pitbulk** [comment]
Request dict is defined [here](https://github.com/onelogin/python3-saml#the-request).
You are right and some extra parameters were added without mention them on docs.

Thanks for mention it. Are you open to contribute to the toolkit with a PR?

**Comment by cjduffett** [comment]
Sure, happy to help. I'll add the three additional parameters mentioned above to the "Request" [section](https://github.com/onelogin/python3-saml#the-request).

**Comment by cjduffett** [comment]
@pitbulk I have a PR ready for these documentation updates. Could you grant me push permissions so I can formally open it?

**Comment by pitbulk** [comment]
you dont need those permission. Just fork the project, create a branch with the changes and create the PR.
