### ISSUE TITLE
Python > 3.3 support

### ISSUE THREAD

**Issue by defionscode** [onelogin/python3-saml#74]
Is there planned support for python versions > 3.3?

**Comment by pitbulk** [comment]
Is not working on python 3.3?

**Comment by defionscode** [comment]
Ah sorry it wasnt clear. I mean support for versions above 3.3, say 3.6 for example.

**Comment by pitbulk** [comment]
I tested it with 3.4 and 3.5 and works.  Maybe I should update travis CI and include those environments to be sure tests pass and then update the description of the project.

But it should work with any python 3.X  if you find any issue, please share.

**Comment by defionscode** [comment]
Ah gotcha, I was going off the docs. I was having issues with 3.6 but due to an issue with xmlsec and not directly with this package.

**Comment by pitbulk** [comment]
Report them directly at
https://github.com/mehcode/python-xmlsec/issues

They will fix them ;)
