### ISSUE TITLE
OneLogin_Saml2_Utils.add_sign Removes the xmlns:xs Namespace, breaking XML schema validation

### ISSUE THREAD

**Issue by cjduffett** [onelogin/python3-saml#76]
## Problem

When using `OneLogin_Saml2_Utils.add_sign` the `xmlns:xs` namespace gets removed from the `<Assertion/>` element. I suspect this happens here: https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/xml_utils.py#L49

As a result, this causes a response signed by this utility to fail validation when passed to `OneLogin_Saml2_Auth.process_response`. Specifically, this is because the xsi:type="xs:string" is not recognized when validating the response against the [AuthnResponse](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/schemas/saml-schema-protocol-2.0.xsd) schema.

## Solution

Don't remove the `xmlns:xs` namespace during the call to `OneLogin_Saml2_XML.to_string` method used by `add_sign`.

**Comment by pitbulk** [comment]
Do you have a PR?
it seems that the cleanup_namespaces method as a parameter keep_ns_prefixes where you can specify don't to remove the xmlns:xs namespace.

**Comment by cjduffett** [comment]
Okay, that's helpful. I can create a PR that adds this to the call to `cleanup_namespaces`.

**Comment by pitbulk** [comment]
any progress on this?

**Comment by cjduffett** [comment]
@pitbulk Thank you for the reminder. Working on this, I'll have a fix for you soon.
