### ISSUE TITLE
Getting error <audience_url> is not a valid audience for this Response

### ISSUE THREAD

**Issue by rajeshyogeshwar** [onelogin/python3-saml#86]
I have found working with this package and onelogin a bit odd at time. Day before yesterday I setup every thing properly, got everything running as well. I saved the configuration from Configuration tab in web portal. Now, when I am trying to login I am getting error saying "XYZ is not a valid audience for this Response". I mean how does it work one time and refuses to work next time with same configuration is a bit odd for me. After tweaking with settings this is how I got it to work first time. But now same set of configuration is not working anymore.

**SAML Consumer URL**
http://mydomain/assertion-consumer-service/

**SAML Single Logout URL**
http://mydomain/logout/

**SAML Audience**
http://mydomain/

**SAML Recipient**
http://mydomain/assertion-consumer-service/

**Comment by pitbulk** [comment]
Something should be changed at OneLogin "configuration" tab, pythin3-saml settings or your server settings.

If your audience is "http://mydomain/" and you get a "XYZ is not a valid audience for this Response"
that means that this value is not configured properly at OneLogin side or at python3-saml side.
