### ISSUE TITLE
"All Rights Reserved"

### ISSUE THREAD

**Issue by dobey** [onelogin/python3-saml#87]
The LICENSE file claims MIT, however all the source files include the following:

> Copyright (c) 2014, OneLogin, Inc.
> All rights reserved.

Please update the source file headers to include the license text, and not say "All rights reserved" to clarify. The year should likely be updated as well to include all the years in which code was committed (and thus published) under this copyright.

This same issue also affects python-saml tree.

**Comment by pitbulk** [comment]
Noted, we will review
