### ISSUE TITLE
Questions about python-saml and python3-saml

### ISSUE THREAD

**Issue by pmariani** [onelogin/python3-saml#9]
Hi,

I am adding SAML SSO to a project and am evaluating python-saml and python3-saml.

So far my project is Python 2/3 compatible and I would like to keep it that way, unless I have a
strong reason to change it.

According to their respective setup.py files, python-saml is Python 2 only while python3-saml is
Python 2 *and* 3, so using python3-saml seems like a good solution for me.

What is the relationship between the 2 projects? It seems that python-saml is more active and more
used than python3-saml. Are features and fixes applied to the first one before getting applied to
the second one later?

For production code, can we rely on python3-saml or should we use python-saml?

I have been using the Pypi version of python3-saml, which is version 1.0.0.
That version has a bug which I am running into which is fixed in the following commit:

```
commit c0a2081aa167aa3b5fb99e8de9f3c4636ca88ed4
Author: Patrick Arminio <patrick.arminio@gmail.com>
Date:   Fri Jan 8 11:32:19 2016 +0100

    Made make_root, make_child and cleanup_namespaces static

diff --git a/src/onelogin/saml2/xml_utils.py b/src/onelogin/saml2/xml_utils.py
index bc7500d..f7f590b 100644
--- a/src/onelogin/saml2/xml_utils.py
+++ b/src/onelogin/saml2/xml_utils.py
@@ -27,9 +27,9 @@ class OneLogin_Saml2_XML(object):
     _unparse_etree = staticmethod(etree.tostring)
 
     dump = staticmethod(etree.dump)
-    make_root = etree.Element
-    make_child = etree.SubElement
-    cleanup_namespaces = etree.cleanup_namespaces
+    make_root = staticmethod(etree.Element)
+    make_child = staticmethod(etree.SubElement)
+    cleanup_namespaces = staticmethod(etree.cleanup_namespaces)
 
     @staticmethod
     def to_string(xml, **kwargs):

```

Python-saml doesn't seem to have that issue.

Is a new version of python3-saml planned to include this fix?

Thank you.

**Comment by pitbulk** [comment]
Hi @pmariani

* Both project are active, I try to push same functionalities on both projects.
* python-saml is older than python3-saml, that is why more people is using it.
* let me publish a new release on pypi.

**Comment by pitbulk** [comment]
New version available:
https://pypi.python.org/pypi/python3-saml/1.1.1

Let me know if you have any other doubt.

**Comment by pmariani** [comment]
Great, thank you! Your responsiveness is greatly appreciated
