### ISSUE TITLE
win7  python3-saml install error

### ISSUE THREAD

**Issue by lilinlichunxiao** [onelogin/python3-saml#91]
How to solve this problem for Very anxious。thank you
LINK : fatal error LNK1159: no output file specified
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX86\\x64\\link.exe' failed with exit status 1159

**Comment by pitbulk** [comment]
how is that error related to python3-saml?

**Comment by lilinlichunxiao** [comment]
When the python3-saml is installing, the error message is prompted, and the C++ compiler is required. 
According to log, the reason was found. xmlsec can not be installed.
Are you able to install xmlsec successfully on windows or Linux systems?

I am Chinese, my English is not good, please forgive me.

**Comment by pitbulk** [comment]
We don't provide support on how to install dependencies. You should try to get support on from the dependency lib community.
