### ISSUE TITLE
auth object given None for get_nameid

### ISSUE THREAD

**Issue by sunilx64** [onelogin/python3-saml#93]
I have setup the SSO as given in the Django example project.
however I facing an issue, 

I am receiving the  correct response from my IDP (ADFS) server. I have tested this using mozila saml tracer.

But when i am trying to get the nameid attribute from auth object it is showing None.

I am assuming when i call init_saml_auth(req) function, it will return unencrypted object. Please correct me if assumption is wrong

**Comment by pitbulk** [comment]
are you not able to use pdb to debug what is going on?

**Comment by sunilx64** [comment]
There was issue in my configuration, it was fixed Thanks
